packages:
  - .

minimumReleaseAgeExclude:
  - "@kubohiroya/turbowarp-svg-text@0.8.1 || 0.10.0"
  - "@kubohiroya/turbowarp-asset-manager@0.13.0 || 0.15.0"
  - "@kubohiroya/turbowarp-runtime-expression@0.4.0 || 0.6.0"
  - "@kubohiroya/turbowarp-async-input@0.5.0 || 0.7.0"
  - "@kubohiroya/vite-plugin-turbowarp-extension@0.4.0"

onlyBuiltDependencies: []
